### ISSUE TITLE
Get Pools fails to return certain tokens since recent stake key changes.

### ISSUE THREAD

**Issue by dpbeaumont** [minswap/blockfrost-adapter#10]
I've noticed when using `getPools` the pools for certain tokens are now not returned, these returned fine a few days ago, tokens affected that I am currently using in my implementation are AADA, AGIX SNEK, WMT.

When investigating further I can see that the pools are queried using the blockfrost method `addressesUtxos` which takes in the MAINNET Pool address in this case `addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxz2j2c79gy9l76sdg0xwhd7r0c0kna0tycz4y5s6mlenh8pq0xmsha`

Which I believe is the wrong pool address now for AGIX etc, resulting in these being filtered out of the response. 

When doing a plain `addressesUtxos` directly using the blockfrost API, with the same parameters as this adapter and then filtering on 'lovelace' and assetB of `f43a62fdc3965df486de8a0d32fe800963589c41b38946602a0dc53541474958` (AGIX's Asset Subject) I can see the pool address was different on the outputs for the AGIX token.  I hope this helps identify pinpoint issue.

**Comment by h2physics** [comment]
@dpbeaumont We're going to work on the breaking change soon. Thanks for your report

**Comment by sampsondaniel** [comment]
Is there a way to get AADA, AGIX & WMT price through the adapter at this moment ?

**Comment by dpbeaumont** [comment]
> Is there a way to get AADA, AGIX & WMT price through the adapter at this moment ?

For me, I manually changed the adapter code, index.js accept a pool address, and my consuming app passes them in based on the ticker, as a temp fix and this works. Took me ages though! I would recommend waiting for the fix.

**Comment by longngn** [comment]
Temporary fix before we find a way to index by script hash: https://github.com/minswap/blockfrost-adapter/issues/10

**Comment by Sluder** [comment]
@longngn A more permanent fix could be to use the Blockfrost endpoint https://docs.blockfrost.io/#tag/Cardano-Assets/paths/~1assets~1%7Basset%7D~1addresses/get, and query addresses holding the token https://cardanoscan.io/token/13aa2accf2e1561723aa26871e071fdf32c867cff7e7d50ad470d62f4d494e53574150

**Comment by longngn** [comment]
> @longngn A more permanent fix could be to use the Blockfrost endpoint https://docs.blockfrost.io/#tag/Cardano-Assets/paths/~1assets~1%7Basset%7D~1addresses/get, and query addresses holding the token https://cardanoscan.io/token/13aa2accf2e1561723aa26871e071fdf32c867cff7e7d50ad470d62f4d494e53574150

that's a fine idea, now I'm thinking about how to implement pagination

**Comment by longngn** [comment]
now track in https://github.com/minswap/blockfrost-adapter/issues/15
