### ISSUE TITLE
Pool.getAmountOut returns strange numbers

### ISSUE THREAD

**Issue by maksymco** [minswap/blockfrost-adapter#12]
When I want to trade 350 ADA for C4 on miniswap it shows me that price impact is 18.72%.

But when I try to use the getAmountOut method it returns strange numbers
`const pool = await this.api.getPoolById({ id: "64c84332705ee884c881219d380349b038e85afe77578ade923107ee1e36da2a"});`
`const { priceImpact, amountOut } = pool.getAmountOut(
      pool.assetA,
      BigInt(350),
);`
`console.log(priceImpact.toString(), amountOut.toString());`

Output for this will be "0.00002304559479445564 0"

So the question is how to calculate price impact by myself or how to use the returned numbers?

**Comment by longngn** [comment]
> 

it should be `350_000_000` because ADA has 6 decimals

**Comment by maksymco** [comment]
Yeap, it works. Thanks and sorry for newbie question
