### ISSUE TITLE
Can not get pool ID

### ISSUE THREAD

**Issue by DeltaChin** [minswap/blockfrost-adapter#13]
Dear,
Months ago I've used below code to get pool ID, but it seems not work recently

`async function runExample() {
  while(true){
  try {

for (let i = 1; ; i++) {
  const pools = await api.getPools({ page: i });
  if (pools.length === 0) {
    // last page
    break;
  }
  const ABPool = (pools.find(
    (p) =>
      p.assetA === "lovelace" &&
      p.assetB ===
        "279c909f348e533da5808898f87f9a14bb2c3dfbbacccd631d927a3f534e454b") //SNEK
  );     
 
    console.log(ABPool);
    break;
  
}

  await delay(10000);

  } catch (err) {
    console.log('error', err);
  }
};
};

runExample();
`

**Comment by longngn** [comment]
> Dear, Months ago I've used below code to get pool ID, but it seems not work recently
> 
> `async function runExample() { while(true){ try {
> 
> for (let i = 1; ; i++) { const pools = await api.getPools({ page: i }); if (pools.length === 0) { // last page break; } const ABPool = (pools.find( (p) => p.assetA === "lovelace" && p.assetB === "279c909f348e533da5808898f87f9a14bb2c3dfbbacccd631d927a3f534e454b") //SNEK );
> 
> ```
> console.log(ABPool);
> break;
> ```
> 
> }
> 
> await delay(10000);
> 
> } catch (err) { console.log('error', err); } }; };
> 
> runExample(); `

you need to pass pool address as well
